### ISSUE TITLE
Finally block does not release jedis resources back to the pool

### ISSUE THREAD

**Issue by abhishek-goyal** [RedisLabs/redis-quartz#11]
Using try with resources just closes the resource defined in the try part and does not return it back to the pool. This leads to pool.getResource() to timeout once the pools connections are exhausted.

`try (Jedis jedis = pool.getResource()) {
    lockPool.acquire();
    // code
} finally {
    lockPool.release();
}`

**Comment by kehati** [comment]
Hi @abhishek-goyal, 

Jedis implements Closable, hence the jedis instance will be auto-closed after the try-with-resource statement.

See the jedis doc: https://github.com/xetorthio/jedis/wiki/Getting-started
See the try-with-resource Oracle's tutorial: https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

**Comment by abhishek-goyal** [comment]
Hi @kehati,

Thanks for your reply. What I am emphasizing is that it won't be freed from the pool that we have defined and are using as we are never calling `pool.returnResource(jedis);`

I think the correct solution here will be to use simple try catch and return the resource in the finally section. This will also help us retain the jedis connection instances to be used by other threads in subsequent calls.

```
final Jedis jedis = pool.getResource();
try {
    ....
} catch (final Exception ex) {
    ....
} finally {
    pool.returnResource(jedis);
}
```

Regards,
Abhishek

**Comment by kehati** [comment]
@abhishek-goyal , please see the correct usage example in the [jedis docs](https://github.com/xetorthio/jedis/wiki/Getting-started):

> /// Jedis implements Closable. Hence, the jedis instance will be auto-closed after the last statement.
try (Jedis jedis = pool.getResource()) {
  /// ... do stuff here ... for example
  jedis.set("foo", "bar");
  String foobar = jedis.get("foo");
  jedis.zadd("sose", 0, "car"); jedis.zadd("sose", 0, "bike"); 
  Set<String> sose = jedis.zrange("sose", 0, -1);
}
/// ... when closing your application:
pool.destroy();

**Comment by abhishek-goyal** [comment]
Was facing this issue while using redis-client 2.4.2, seems like they have changed the behavior moving forward to 2.9.0, thanks for clarifying.
