### ISSUE TITLE
GPL and Java

### ISSUE THREAD

**Issue by avram** [RedisLabs/redis-quartz#3]
By the standard interpretation of the GPL with regard to Java libraries, I can't use this data store in a non-GPL application: https://www.gnu.org/licenses/lgpl-java.html

I would love to use this job store, but my application is not GPL-licensed and will not become GPL-licensed.

**Comment by kehati** [comment]
Hi @avram, thanks for your comment!
I wanted to let you know that we are thinking about switching the license to a more permissive one. I'll let you know once we have a decision.

**Comment by avram** [comment]
Thanks! MIT is a much better fit for many of your happy Redis Labs users, and I'll see about replacing Postgres with Redis for our Quartz instances as well!
